# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acp_calendar', '0002_load_holiday_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acpholiday',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='acpholiday',
            name='date',
            field=models.DateField(unique=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='acpholiday',
            name='holiday_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acp_calendar.HolidayType', verbose_name='Holiday type'),
        ),
        migrations.AlterField(
            model_name='holidaytype',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Holiday name'),
        ),
    ]
